repos:
  # imports
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    - id: isort
      additional_dependencies: [toml]
      exclude: examples/*
  # types
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'
    hooks:
    - id: mypy
      language_version: python3
      args: [--no-strict-optional, --ignore-missing-imports, --show-traceback, --install-types, --non-interactive]
      exclude: docs/*
  # code style
  - repo: https://github.com/python/black
    rev: 22.6.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/pylint
    rev: v2.14.5
    hooks:
    - id: pylint
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
  # notebooks
  - repo: https://github.com/s-weigand/flake8-nb
    rev: v0.5.2
    hooks:
    - id: flake8-nb
      files: \.ipynb$
  # documentation
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
    - id: interrogate
      exclude: ^(build|docs|merlin/io|tests|setup.py|versioneer.py)
      args: [--config=pyproject.toml]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.1
    hooks:
    - id: codespell
  # security
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      args: [--verbose, -ll, -x, tests,examples,bench]
