# Copyright (c) 2022, NVIDIA CORPORATION.

# Usage:
#   conda build . -c defaults -c conda-forge -c numba -c rapidsai


{% set version = environ.get('GIT_DESCRIBE_TAG', '0.1').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set setup_py_data = load_setup_py_data() %}


package:
  name: merlin-core
  version: {{ version }}

source:
  path: ../../

build:
  number: {{ git_revision_count }}
  noarch: python
  script: python -m pip install . -vvv

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    {% for req in setup_py_data.get('install_requires', []) %}
    - {{ req }}
    {% endfor %}
    - dask-cudf>=21.10.*
    - cupy>=7.2.0,<10.0.0a
    - nvtx>=0.2.1

about:
  home: https://github.com/NVIDIA-Merlin/core
  license_file: LICENSE
  summary: Core Utilities for NVIDIA Merlin
