name: Systems Tests (CPU)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - v*
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Ubuntu packages
      run: |
        sudo apt-get update -y
        sudo apt-get install -y protobuf-compiler
    - name: Install and upgrade python packages
      run: |
        python -m pip install --upgrade pip setuptools==59.4.0 wheel tox
    - name: Run tests
      run: |
        GIT_COMMIT=`git rev-parse HEAD` tox -e test-systems-cpu
