name: Core Tests (CPU)

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - v*
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/tox.yml
    with:
      env: test-cpu

  store-pr-information:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Store PR information
        run: |
          mkdir ./pr
          echo ${{ github.event.number }}              > ./pr/pr.txt
          echo ${{ github.event.pull_request.merged }} > ./pr/merged.txt
          echo ${{ github.event.action }}              > ./pr/action.txt
      - name: Upload PR information
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/

      # Build docs, treat warnings as errors
      - name: Building docs
        run: |
          tox -e docs
      - name: Upload HTML
        uses: actions/upload-artifact@v3
        with:
          name: html-build-artifact
          path: docs/build/html
          if-no-files-found: error
          retention-days: 1
