name: docs-preview-pr

on:
  pull_request:
    branches: [main]

env:
  WF_ID: ${{ github.event.pull_request.id }}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Building Docs
        run: |
          tox -e docs
      - name: Upload HTML Required by Preview Workflow
        uses: actions/upload-artifact@v3
        with:
          name: html-build-artifact
          path: docs/build/html
          if-no-files-found: error
          retention-days: 1
      - name: Store PR information
        run: |
          mkdir ./pr
          echo ${{ github.event.number }}              > ./pr/pr.txt
          echo ${{ github.event.pull_request.merged }} > ./pr/merged.txt
          echo ${{ github.event.action }}              > ./pr/action.txt
      - name: Upload PR information
        uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/

  preview:
    needs: [build-docs]
    uses: nvidia-merlin/.github/.github/workflows/docs-preview-pr-common.yaml@docs-preview-remove-workflow-run-condition
    with:
      workflow-id: "${{ github.event.pull_request.id }}"
