name: GPU CI

on:
  push:
    branches:
      - "pull-request/[0-9]+"

jobs:
  gpu-ci-docker:
    runs-on: linux-amd64-gpu-p100-latest-1

    container:
      image: nvcr.io/nvstaging/merlin/merlin-ci-runner:latest
      credentials:
        username: ${{ secrets.SVC_DOCKER_USER }}
        password: ${{ secrets.SVC_DOCKER_TOKEN }}
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: .tox
          key: tox-${{ matrix.image }}-${{ hashFiles('requirements/*.txt') }}
      - name: Get Branch name
        id: get-branch-name
        uses: NVIDIA-Merlin/.github/actions/branch-name@6f0539fba24f60da2aee63c5925bee7cee3206e3
      - name: Run tests
        run: |
          merlin_branch="${{ steps.get-branch-name.outputs.branch }}"
          MERLIN_BRANCH=$merlin_branch COMPARE_BRANCH=$merlin_branch \
            tox -e gpu
