name: "Reusable Workflow - Run Tox Env (1GPU)"

on:
  workflow_call:
    inputs:
      env:
        description: "The name of the tox environment to run"
        required: true
        type: string

jobs:
  check:
    runs-on: 1GPU

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          ref_type=${{ github.ref_type }}
          branch=main
          if [[ $ref_type == "tag"* ]]
          then
            raw=$(git branch -r --contains ${{ github.ref_name }})
            branch=${raw/origin\/}
          fi
          GIT_COMMIT=`git rev-parse HEAD` tox -e ${{ inputs.env }} -- $branch
