name: "Run Tox Env"

on:
  workflow_call:
    inputs:
      env:
        description: "The name of the tox environment to run"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Ubuntu packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y protobuf-compiler
      - name: Install and upgrade python packages
        run: |
          python -m pip install --upgrade pip setuptools==59.4.0 wheel tox
      - name: Get Branch name
        id: get-branch-name
        uses: NVIDIA-Merlin/.github/actions/branch-name@main
      - name: Run tests
        run: |
          branch="${{ steps.get-branch-name.outputs.branch }}"
          GIT_COMMIT=`git rev-parse HEAD` tox -e ${{ inputs.env }} -- $branch
